/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerTarefas;

/**
 *
 * @author Thiag
 */
public class ViewTarefasAdicionarTarefa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewTarefasAdicionarTarefa.class.getName());

    /**
     * Creates new form ViewTarefasAdicionarTarefa
     */
    public ViewTarefasAdicionarTarefa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelAdicionarTarefa = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        caixaDeTextoTitulo = new javax.swing.JTextField();
        caixaDeTextoDescricaoDaTarefa = new javax.swing.JTextField();
        labelTitulo1 = new javax.swing.JLabel();
        labelTitulo2 = new javax.swing.JLabel();
        caixaDeTextoStatus = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(169, 198, 224));

        labelAdicionarTarefa.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        labelAdicionarTarefa.setForeground(new java.awt.Color(0, 82, 236));
        labelAdicionarTarefa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAdicionarTarefa.setText("Adicionar tarefa");

        labelTitulo.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 82, 236));
        labelTitulo.setText("Título");

        caixaDeTextoTitulo.setBackground(new java.awt.Color(169, 198, 224));
        caixaDeTextoTitulo.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        caixaDeTextoTitulo.setForeground(new java.awt.Color(102, 102, 102));
        caixaDeTextoTitulo.setText("Digite aqui...");
        caixaDeTextoTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 82, 236), 2));
        caixaDeTextoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaDeTextoTituloActionPerformed(evt);
            }
        });

        caixaDeTextoDescricaoDaTarefa.setBackground(new java.awt.Color(169, 198, 224));
        caixaDeTextoDescricaoDaTarefa.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        caixaDeTextoDescricaoDaTarefa.setForeground(new java.awt.Color(102, 102, 102));
        caixaDeTextoDescricaoDaTarefa.setText("Digite aqui...");
        caixaDeTextoDescricaoDaTarefa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 82, 236), 2));
        caixaDeTextoDescricaoDaTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaDeTextoDescricaoDaTarefaActionPerformed(evt);
            }
        });

        labelTitulo1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        labelTitulo1.setForeground(new java.awt.Color(0, 82, 236));
        labelTitulo1.setText("Status");

        labelTitulo2.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        labelTitulo2.setForeground(new java.awt.Color(0, 82, 236));
        labelTitulo2.setText("Descrição da tarefa");

        caixaDeTextoStatus.setBackground(new java.awt.Color(169, 198, 224));
        caixaDeTextoStatus.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        caixaDeTextoStatus.setForeground(new java.awt.Color(102, 102, 102));
        caixaDeTextoStatus.setText("Digite aqui...");
        caixaDeTextoStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 82, 236), 2));
        caixaDeTextoStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaDeTextoStatusActionPerformed(evt);
            }
        });

        botaoSalvar.setBackground(new java.awt.Color(169, 198, 224));
        botaoSalvar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botaoSalvar.setForeground(new java.awt.Color(51, 255, 102));
        botaoSalvar.setText("SALVAR");
        botaoSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAdicionarTarefa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(487, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caixaDeTextoTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaDeTextoDescricaoDaTarefa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaDeTextoStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(528, 528, 528))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTitulo2)
                        .addGap(475, 475, 475))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(565, 565, 565)
                        .addComponent(labelTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(557, 557, 557)
                        .addComponent(labelTitulo1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoSalvar)
                .addGap(71, 71, 71))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(labelAdicionarTarefa)
                .addGap(56, 56, 56)
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addComponent(caixaDeTextoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTitulo2)
                .addGap(18, 18, 18)
                .addComponent(caixaDeTextoDescricaoDaTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTitulo1)
                .addGap(18, 18, 18)
                .addComponent(caixaDeTextoStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(botaoSalvar)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caixaDeTextoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaDeTextoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaDeTextoTituloActionPerformed

    private void caixaDeTextoDescricaoDaTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaDeTextoDescricaoDaTarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaDeTextoDescricaoDaTarefaActionPerformed

    private void caixaDeTextoStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaDeTextoStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaDeTextoStatusActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
       String titulo = caixaDeTextoTitulo.getText();
       String descricao = caixaDeTextoDescricaoDaTarefa.getText();
       String status = caixaDeTextoStatus.getText();
       
       ControllerTarefas controller = new ControllerTarefas();
       
       boolean sucesso = controller.cadastrarTarefa (titulo, descricao, status);
       
       if (sucesso) {
        this.dispose();
       }
        
    }//GEN-LAST:event_botaoSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewTarefasAdicionarTarefa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField caixaDeTextoDescricaoDaTarefa;
    private javax.swing.JTextField caixaDeTextoStatus;
    private javax.swing.JTextField caixaDeTextoTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAdicionarTarefa;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTitulo1;
    private javax.swing.JLabel labelTitulo2;
    // End of variables declaration//GEN-END:variables
}
