/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import model.ModelTarefas;


/**
 *
 * @author Thiag
 */
public class ViewTarefasTelaMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewTarefasTelaMenu.class.getName());

    /**
     * Creates new form ViewTarefasTelaInicial
     */
    public ViewTarefasTelaMenu() {
        initComponents();
        preencherTabela();
        final ViewTarefasTelaMenu janelaPrincipal = this;
        
        tabelaDeTarefas.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getClickCount() == 2) { // Duplo clique
            
            int linha = tabelaDeTarefas.getSelectedRow();
            if (linha != -1) {

    // 1. PRIMEIRO: Pegar os dados da tabela (Movemos isto para cima)
    int id = Integer.parseInt(tabelaDeTarefas.getValueAt(linha, 0).toString());
    String titulo = tabelaDeTarefas.getValueAt(linha, 1).toString();
    String descricao = tabelaDeTarefas.getValueAt(linha, 2).toString();
    String status = tabelaDeTarefas.getValueAt(linha, 3).toString();

    // 2. DEPOIS: Criar a tarefa passando os 4 dados OBRIGATÓRIOS
    // Repara que agora os dados vão dentro dos parênteses ( )
    model.ModelTarefas tarefaSelecionada = new model.ModelTarefas(id, titulo, descricao, status);
    

    // 3. Abrir a nova janela
    janelaPrincipal.dispose();
    ViewTarefasDetalhes tela = new ViewTarefasDetalhes(tarefaSelecionada);
    
    tela.setVisible(true);
    
       }
            
            
        }
        
    }
});
        
        
        
        tabelaDeTarefas.getColumnModel().getColumn(1).setCellRenderer(new javax.swing.table.DefaultTableCellRenderer() {
        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            
            // 1. Cria a célula padrão (texto numa linha só)
            super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            // 2. O Segredo: Define o texto do balãozinho igual ao texto da célula
            if (value != null) {
                setToolTipText(value.toString()); // Isto cria o popup amarelo
            } else {
                setToolTipText(null);
            }
            
            return this;
        }
    });
    
    
        tabelaDeTarefas.getColumnModel().getColumn(2).setCellRenderer(new javax.swing.table.DefaultTableCellRenderer() {
        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            
            // 1. Cria a célula padrão (texto numa linha só)
            super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            // 2. O Segredo: Define o texto do balãozinho igual ao texto da célula
            if (value != null) {
                setToolTipText(value.toString()); // Isto cria o popup amarelo
            } else {
                setToolTipText(null);
            }
            
            return this;
        }
    });
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jPanel1 = new javax.swing.JPanel();
        labelGerenciadorDeTarefas = new java.awt.Label();
        botaoAdicionarTarefa = new javax.swing.JButton();
        botaoEditarTarefa = new javax.swing.JButton();
        botaoApagarTarefa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaDeTarefas = new javax.swing.JTable();

        popupMenu1.setLabel("popupMenu1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(169, 198, 224));

        labelGerenciadorDeTarefas.setAlignment(java.awt.Label.CENTER);
        labelGerenciadorDeTarefas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelGerenciadorDeTarefas.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        labelGerenciadorDeTarefas.setForeground(new java.awt.Color(0, 82, 236));
        labelGerenciadorDeTarefas.setText("Bem vindo ao seu gerenciador de tarefas, usuário");

        botaoAdicionarTarefa.setBackground(new java.awt.Color(169, 198, 224));
        botaoAdicionarTarefa.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        botaoAdicionarTarefa.setForeground(new java.awt.Color(0, 82, 236));
        botaoAdicionarTarefa.setText("Adicionar tarefa");
        botaoAdicionarTarefa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoAdicionarTarefa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoAdicionarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarTarefaActionPerformed(evt);
            }
        });

        botaoEditarTarefa.setBackground(new java.awt.Color(169, 198, 224));
        botaoEditarTarefa.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        botaoEditarTarefa.setForeground(new java.awt.Color(0, 82, 236));
        botaoEditarTarefa.setText("Editar tarefa");
        botaoEditarTarefa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoEditarTarefa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoEditarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarTarefaActionPerformed(evt);
            }
        });

        botaoApagarTarefa.setBackground(new java.awt.Color(169, 198, 224));
        botaoApagarTarefa.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        botaoApagarTarefa.setForeground(new java.awt.Color(0, 82, 236));
        botaoApagarTarefa.setText("Apagar tarefa");
        botaoApagarTarefa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoApagarTarefa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoApagarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoApagarTarefaActionPerformed(evt);
            }
        });

        tabelaDeTarefas.setAutoCreateRowSorter(true);
        tabelaDeTarefas.setBackground(new java.awt.Color(169, 198, 224));
        tabelaDeTarefas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 112, 182)));
        tabelaDeTarefas.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        tabelaDeTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Título", "Descrição da Tarefa", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaDeTarefas.setToolTipText("");
        tabelaDeTarefas.setAlignmentX(1.0F);
        tabelaDeTarefas.setAlignmentY(1.0F);
        tabelaDeTarefas.setDoubleBuffered(true);
        tabelaDeTarefas.setGridColor(new java.awt.Color(255, 255, 255));
        tabelaDeTarefas.setPreferredSize(new java.awt.Dimension(400, 400));
        tabelaDeTarefas.setRowHeight(50);
        tabelaDeTarefas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaDeTarefas.setShowHorizontalLines(true);
        tabelaDeTarefas.setShowVerticalLines(true);
        jScrollPane2.setViewportView(tabelaDeTarefas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoApagarTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEditarTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAdicionarTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
            .addComponent(labelGerenciadorDeTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, 1248, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelGerenciadorDeTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(botaoEditarTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(botaoApagarTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(botaoAdicionarTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAdicionarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarTarefaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
   
    }//GEN-LAST:event_botaoAdicionarTarefaActionPerformed

    private void botaoEditarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarTarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEditarTarefaActionPerformed

    private void botaoApagarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoApagarTarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoApagarTarefaActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        preencherTabela();
        
    }//GEN-LAST:event_formWindowGainedFocus
 private void preencherTabela(){
// 1. Chama o controller

    controller.ControllerTarefas controller = new controller.ControllerTarefas();
    
    // 2. BUSCA A LISTA NO BANCO (Esta é a linha que estava faltando!)
    java.util.List<model.ModelTarefas> listaTarefas = controller.listaTarefas();
    
    // 3. Prepara a tabela para receber dados
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tabelaDeTarefas.getModel();
    modelo.setNumRows(0); // Limpa a tabela antes de encher
    
    // 4. Teste do Detetive (opcional, para ver no Output)
    System.out.println("Encontrei " + listaTarefas.size() + " tarefas.");

    // 5. Adiciona cada tarefa nas linhas da tabela
    for (model.ModelTarefas tarefa : listaTarefas) {
        modelo.addRow(new Object[]{
            tarefa.getId(),
            tarefa.getTitulo(),
            tarefa.getDescricao(),
            tarefa.getStatus()
        });
    }
}        
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewTarefasTelaMenu().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionarTarefa;
    private javax.swing.JButton botaoApagarTarefa;
    private javax.swing.JButton botaoEditarTarefa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label labelGerenciadorDeTarefas;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTable tabelaDeTarefas;
    // End of variables declaration//GEN-END:variables
}
